[package]
name = "packing_spectral"
version = "0.1.0"
authors = ["Timothy Middlemas <tm17@princeton.edu>"]
edition = "2018"

[dependencies]
rayon = "1.0"
chrono = "0.4"
structopt = "0.2"
nalgebra = "0.18.0"
typenum = "1.10.0"
