#!/usr/bin/env python3
import sys

if __name__ == "__main__":
    infile = open(sys.argv[1])
    for i in range(4):
        infile.readline()
    acc = 0.0
    n = 0.0
    for line in infile:
        tokens = line.split()
        acc += float(tokens[3])
        n += 1.0
    print(acc/n)

